# -*- coding: utf-8 -*-
"""FakeNewsDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zISmE5HJ9MFaSsFt731FskeaVpYU82d8
"""

import pandas as pd
import numpy as np
import streamlit as st
import pickle

model = pickle.load(open("model.pkl", "rb"))

st.title("Fake News Detection")

news = st.text_area("Enter News Article")

if st.button("Predict"):
    prediction = model.predict([news])
    st.write("Prediction:", prediction[0])
fake=pd.read_csv('/content/Fake.csv.zip')

true=pd.read_csv('/content/True.csv.zip')

true.head()

fake.head()

true['label']=1

fake['label']=0;

news=pd.concat([fake,true],axis=0)

news.tail()

news

news.isnull().sum()

columns_to_drop = ['title', 'subject', 'date']
existing_columns = [col for col in columns_to_drop if col in news.columns]
if existing_columns:
    news = news.drop(existing_columns, axis=1)

news

# news=news.drop(['index'],axis=1,inplace=True) # This line caused a KeyError because the 'index' column does not exist.

news

news = news.sample(frac=1).reset_index(drop=True)

news

news.head()

import re

def wordopt(text):
  text = text.lower()
  # Remove URLs
  text = re.sub(r'https?://\S+|www\.\S+', '', text)
  # Remove HTML tags
  text = re.sub(r'<.*?>', '', text)
  # Remove digits
  text = re.sub(r'\d', '', text)
  # Remove punctuation and special characters, but keep spaces
  text = re.sub(r'[^a-zA-Z\s]', ' ', text)
  # Remove newlines
  text = re.sub(r'\n', ' ', text)
  # Remove extra spaces
  text = re.sub(r'\s+', ' ', text).strip()
  return text

news['text']=news['text'].apply(wordopt)

news['text']=news['text'].apply(wordopt)

news['text']

x=news['text']
y=news['label']
x

y

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

x_train.shape

y_train.shape

from sklearn.feature_extraction.text import TfidfVectorizer
vectorization=TfidfVectorizer()
xv_train=vectorization.fit_transform(x_train)
xv_test=vectorization.transform(x_test)

xv_train

xv_test

from sklearn.linear_model import LogisticRegression

reg=LogisticRegression()
reg.fit(xv_train,y_train)

predict=reg.predict(xv_test)

predict

reg.score(xv_test,y_test)

from sklearn.metrics import classification_report
print(classification_report(y_test,predict))

from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(xv_train,y_train)

pred_dct=dt.predict(xv_test)
pred_dct

dt.score(xv_test,y_test)

print(classification_report(y_test,pred_dct))

from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(xv_train,y_train)

pred_rfc=rfc.predict(xv_test)
pred_rfc

rfc.score(xv_test,y_test)

print(classification_report(y_test,pred_rfc))

from sklearn.ensemble import GradientBoostingClassifier
gbc=GradientBoostingClassifier()
gbc.fit(xv_train,y_train)

pred_gbc=gbc.predict(xv_test)
pred_gbc

gbc.score(xv_test,y_test)

print(classification_report(y_test,pred_gbc))

def ouput_label(n):
  if n==0:
    return "It is a fake news"
  elif n==1:
    return "It is a genuine news"

def manual_testing(news):
  testing_news={"text":[news]}
  new_def_test=pd.DataFrame(testing_news)
  new_def_test["text"]=new_def_test["text"].apply(wordopt)
  new_x_test=new_def_test["text"]
  new_xv_test=vectorization.transform(new_x_test)
  predict=reg.predict(new_xv_test)
  pred_rfc=rfc.predict(new_xv_test)
  pred_dct=dt.predict(new_xv_test)
  pred_gbc=gbc.predict(new_xv_test)
  print("\n\nLogistic Regression Prediction: {} ".format(ouput_label(predict[0])))
  print("\n\nRandom Forest Prediction:{}".format(ouput_label(pred_rfc[0])))
  print("\n\nDecision Tree Prediction:{}".format(output_label(pred_dct[0])))
  print("\n\nGradient Boosting Prediction:{}".format(output_label(pred_gbc[0])))

